
services:
  db:
    image: mysql:8.0
    container_name: soccer_mysql
    restart: always
    environment:
      MYSQL_DATABASE: soccer_db
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      # เก็บข้อมูลไว้ในเครื่องเรา (ข้อมูลจะไม่หายเวลาปิด Docker)
      - mysql_data:/var/lib/mysql
      - ./backend/uploads:/app/uploads
      # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: