services:
  db:
    image: postgres:15-alpine  # เปลี่ยนจาก mysql เป็น postgres
    container_name: soccer-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=YourStrongPassword123
      - POSTGRES_DB=soccer_db
    ports:
      - "5432:5432"  # พอร์ตมาตรฐานของ Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: